version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: watersys
    ports:
      - "5432:5432"
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: watersys
  
  script-executor:
    build:
      context: .  # Diretório onde o Dockerfile está localizado
      dockerfile: Dockerfile-script  # Nome do arquivo Dockerfile
    depends_on:
      - postgres
      - app
