version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: watersys
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: watersys
  
  script-executor:
    build:
      context: .
      dockerfile: Dockerfile-script
    depends_on:
      - postgres
      - app

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile  # Use o mesmo Dockerfile que você usa para o seu app principal
    ports:
      - "8501:8501"  # Mapeie a porta do Streamlit para o host
    depends_on:
      - postgres
      - app
      - script-executor
    command: streamlit run /app/dashboards.py
