version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: mydb

  mysql:
    image: mysql:latest
    container_name: meu-mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin-root
      MYSQL_DATABASE: mydb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - /home/george/Área de Trabalho/watersys/database/data:/var/lib/mysql #substituir pelo caminho da sua maquina
      - ./initdb:/docker-entrypoint-initdb.d
