FROM python:3.11.2-slim-bullseye
WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt


COPY make_tables.py /app/make_tables.py

COPY . .

CMD ["python3", "/app/make_tables.py"]
